### ISSUE TITLE
Tor usage during the wallet creation

### ISSUE THREAD

**Issue by hellc** [vergecurrency/vIOS#104]
**Describe the bug**
Some server endpoints is not accessible from countries with network censorship.
Need to fix Tor usage during the wallet creation phase.

**To Reproduce**
1. Come to Russia
2. Try to create a wallet from scratch
<img width="232" height="412" alt="screenshot 2019-01-23 at 3 25 34 am" src="https://user-images.githubusercontent.com/750178/51609562-806a0f80-1f2b-11e9-8457-e6689894972d.gif">

**Comment by marpme** [comment]
Well for this we would need support for: https://bridges.torproject.org/bridges?transport=obfs4

But this isn't a good solution, so the only way to create your wallet at this point is to disable tor, I guess.

**Comment by hellc** [comment]
> Well for this we would need support for: https://bridges.torproject.org/bridges?transport=obfs4
> 
> But this isn't a good solution, so the only way to create your wallet at this point is to disable tor, I guess.

It's not about Tor. Tor should solve this problem. But seems like it's bug right now, thats why we need to fix it. Tor works fine in Russia (even w/o bridges). @SwenVanZanten knows about this problem

**Comment by marpme** [comment]
Oh okay, then sorry. I misunderstood your problem.
