### ISSUE TITLE
Stuck transaction

### ISSUE THREAD

**Issue by cidadededeus36** [vergecurrency/vIOS#109]
**Describe the bug**
I have a transaction that is currently stuck. It's been approximately 7 hrs since I've sent my transaction. I tried removing the transaction using the trash can icon on the top right corner of the transaction only for it to return in my transaction list upon restart of wallet.  The transaction ID given in the wallet is not showing up in the block explorer. I've looked into all my previous receive addresses in the block explorer and my coins seem to still be unmoved from my addresses. Does this means my funds are retrievable or are they lost in limbo? I tried entering my mnemonic in another wallet but realized my mnemonic is only 12 words plus a passphrase. I believe the other wallets are 24 word mnemonic.

**To Reproduce**
Not sure if this exactly reproduces the behavior or not...
these are just steps i took prior to having a stuck transaction.

1. Send multiple transaction to the wallet using multiple different receive addresses.
2. Once receive transactions are confirmed.
3. Go to the send screen.
4. Select an address from one of your saved contacts.
5. For the amount press the Send Max button.
6. Send.
7. Go to the transaction list.
8. Transaction will have the satellite logo to the left of it and will not confirm nor will the trans id be in the block explorer.

**Expected behavior**
I expect the wallet to send my transaction and confirm.

**Smartphone (please complete the following information):**
 - Device: iPhone 7
 - OS: iOS 12.1.3
 - iOS Wallet: v0.14-beta.2

**Comment by cidadededeus36** [comment]
Updated to the latest Verge Wallet 0.15. Transaction is still listed as stuck. Maybe it's an issue with the verge wallet services?

**Comment by SwenVanZanten** [comment]
This was solved by using the right amount of transaction fee.
