### ISSUE TITLE
Tor not allowing http requests

### ISSUE THREAD

**Issue by FontaineDenton** [vergecurrency/vIOS#163]
I am trying to access a V3 hidden service using your TorClient code and it is working great in the simulator but not on the device which is very strange.

Simulator: everything works.

Device: only HTTPS requests work :(

Do you have any idea why that would be the case?

Thank you for your time.

**Comment by marpme** [comment]
Swift/iOS disallows any non-HTTPS requests on production-ready devices due to the complication that could be caused by using plaintext HTTP request

See: https://stackoverflow.com/a/35104152/4479618

**Comment by FontaineDenton** [comment]
Yes I have set the "allows arbitrary loads" to true in my info.plist. Just wondering if you have had any success using the tor framework with non https requests as I am stuck. If you have any other suggestions that would be appreciated.

**Comment by marpme** [comment]
We just don’t use HTTP and it’s not even recommended to do so.
I guess it’s easier to upgrade the certificate than bringing swift to use HTTP requests

**Comment by FontaineDenton** [comment]
So actually Ive tried https request to onion site as well and that also does not work with the implementation of tor.framework, it only works on simulator for onion sites. I know its out of the scope of your app. I am just trying to solve this, if you figure out a solution please do let me know.

**Comment by marpme** [comment]
I would kindly forward you to the framework repo instead of posting this here as you already stated that this is out of scope for us. And we won't have any further look into it. Sorry.

**Comment by justinvforvendetta** [comment]
@FontaineDenton what are you trying to accomplish

**Comment by FontaineDenton** [comment]
@justinvforvendetta Assume a user has a V3 hidden service running that controls their Bitcoin Core RPC port for their full node. I want to allow users to connect to their V3 hidden service in my app https://github.com/FontaineDenton/FullyNoded to allow people to use their nodes securely on an iPhone. I have it working really well in simulator but not at all on the device for hidden services. I am reaching out on the Tor.framework project and others too, I am very keen to figure out what the issue is and how I can fix it.
