### ISSUE TITLE
blurry the program when it enter background

### ISSUE THREAD

**Issue by TheWanderingCoel** [vergecurrency/vIOS#174]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
```
Add some code in AppDelegate.swift to achieve this
```

**Describe alternatives you've considered**

**Additional context**
Like this:
![Blurry](https://img-blog.csdn.net/20180807104143738?watermark/2/text/aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dhbmd4aW54dTUyMQ==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70)

**Comment by SwenVanZanten** [comment]
But the unlock view is already shown.
Why should we also blur it?
Seems a bit redundant.

![image](https://user-images.githubusercontent.com/3099122/62847165-28cb9f80-bcd5-11e9-93db-6fbd7050094a.png)

**Comment by TheWanderingCoel** [comment]
Yeah, I truly agree with that. I'm considering an experimental option that allow user choose lock their wallet or not. That may be the only way blurry can be useful.

**Comment by SwenVanZanten** [comment]
Don't think its wise to add a feature because you want to blur the background :D
Unlocked wallets aren't a good idea. I'm closing this for now.
