### ISSUE TITLE
Unexpectedly nil while unwrapping - SetAmountViewController

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/vIOS#21]
SetAmountViewController.swift
<img width="864" alt="screen shot 2018-08-25 at 1 20 17 pm" src="https://user-images.githubusercontent.com/35063339/44620858-bf574480-a869-11e8-91a4-252b74aad99b.png">

When attempting to put a decimal amount of XVG program crashes, replicate by attempting to send and writing "0.1".

**Comment by marpme** [comment]
Gonna have that when you start with a `.` on the send page

Secondly you can set the amount within the settings page.

**Comment by SwenVanZanten** [comment]
Fixed in latest commit
