### ISSUE TITLE
Send Panel XVG Amount

### ISSUE THREAD

**Issue by marpme** [vergecurrency/vIOS#62]
**Describe the bug**
When creating a new transaction to someone you have the card showing your current balance but that one is off.

**To Reproduce**
1. Create a new transaction 
2. Add an amount to send to someone
3. `Current balance - send amount` is incorrect as fee has to be applied somewhere

**Expected behavior**
Should show `currentBalance - (sendAmount + fee)`

**Screenshots**
none.

**Smartphone (please complete the following information):**
irrelevant

**Comment by marpme** [comment]
Okay then it's maybe not a bug, but rather a visual improvements as it wasn't quite clear to me that the fee was already deducted from the currently available balance 🌮

**Comment by SwenVanZanten** [comment]
Fixed
