### ISSUE TITLE
Send Tab isn't refreshing after confirmed TX

### ISSUE THREAD

**Issue by xvgrkt** [vergecurrency/vIOS#63]
**Describe the bug**
After receiving 10 XVG, had to fully close the app and re-open to be able to send XVG again.

**To Reproduce**
1. Receive xxx XVG
2. Go to Send tab
3. No balance displayed

**Expected behavior**
Receive XVG, go to Send tab, see updated balance or refreshed wallet balance, and send XVG to an address

**Screenshots**
1. Positive balance - [screen 1](https://imgur.com/twZuV14) ![1 pos bal](https://user-images.githubusercontent.com/38752123/50718926-10652800-10e9-11e9-9d0b-1d6e4e2a282e.png)

2. "Not enough balance" when there is available funds to send - [screen 2](https://imgur.com/su6fYaX)
![2 no ref bal](https://user-images.githubusercontent.com/38752123/50718927-10652800-10e9-11e9-8570-c4b9a2db7398.png)

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS Version 12.1.2

**Comment by marpme** [comment]
I guess here and would say the check wasn't intended like that:

https://github.com/vergecurrency/vIOS/blob/5ed0c02327c9f81ba28eb70fd19c5bfd0186d8c1/VergeiOS/Views/Send/SendViewController.swift#L73

But It's actually weird that I've seen some people being able to send something even with this strict statement

**Comment by SwenVanZanten** [comment]
Fixed
