### ISSUE TITLE
Multiple wallets

### ISSUE THREAD

**Issue by SwenVanZanten** [vergecurrency/vIOS#75]
Have the possibility to add multiple wallets.
So it can be used as a savings, house, sharing account etc.

### Todo:
- [ ] Create a design for allowing multiple wallets.
- [ ] Rewrite storage for wallet keys & transactions.

**Comment by marpme** [comment]
Regarding that no new wallet needed.

if you have your public key identifier, you can switch `xpub/X/Y`
where `X` is the account identifier and `Y` represents the generated address for either account

**Comment by SwenVanZanten** [comment]
That's not really bws compatible.

**Comment by SwenVanZanten** [comment]
Will be implemented in v2.0.0
