### ISSUE TITLE
Contrast of QR code is to low for Android

### ISSUE THREAD

**Issue by SwenVanZanten** [vergecurrency/vIOS#78]

**Comment by SwenVanZanten** [comment]
Fixed thanks to **The Verge Dealer** @vilacamoreira

**Comment by Max1us** [comment]
[Beta2] If I didn't have the ipad brightness up full, I still couldn't get the QR codes to be recognised by Coinomi or QR Code Pro [Android / Galaxy S7]. 

Perhaps add some kind of helper note somewhere to advise the user to try altering the brightness if experiencing issues?
