### ISSUE TITLE
Update address validator

### ISSUE THREAD

**Issue by hellc** [vergecurrency/vIOS#84]
Based on comment https://github.com/vergecurrency/vIOS/pull/83#issuecomment-452429886

> Well the address could be checked if more detailed, via decoding it from base58
> 
> 1. Remove the last 4 bytes of the decoded byte array (store it, it's the checksum)
> 2. Take the rest of the array and do `let checksum = sha256(sha256(restArray))`
> 3. Check if valid `checksumStored == checksum[0..8]`
> 4. and the first byte of the array determines the network (for us it must be 0x33)
> 
> you can play around with an bitcoin example here: http://gobittest.appspot.com/Address

**Comment by SwenVanZanten** [comment]
Fixed with validating with https://github.com/vergecurrency/BitcoinKit/blob/d737a47ce1e4eefc0a69bac10bf40b6cfeef0bd7/Sources/BitcoinKit/Core/Keys/Address.swift#L69
