### ISSUE TITLE
Amount being sent rounds down - not exactly what you specify

### ISSUE THREAD

**Issue by Max1us** [vergecurrency/vIOS#90]
**Describe the bug**
When sending an XVG amount with 8 decimal places, the wallet rounds down the amount sent.
You only see the rounded amount on the transaction history - at every stage up until then, you see the expected amount that you input.

**To Reproduce**

Test 1
1. Sent 1.5318008 xvg to an address.
2. Wallet showed this amount everywhere.. transaction is now complete.
3. Go to the entry in your transaction history list
4. The actual amount sent was 1.123456

Test 2
1. Sent 1.5318008 xvg to an address.
2. Wallet showed this amount everywhere.. transaction is now complete.
3. Go to the entry in your transaction history list
4. The actual amount sent was 1.5318

The rounded amounts are actually what was sent, verified by the txid on blockchain. Not just a visual rounding issue.

**Expected behavior**
Send the exact amount entered.

**Smartphone (please complete the following information):**

**Comment by Max1us** [comment]
@SwenVanZanten 
Ah yeah, cut n paste typo in the description.. oops. Meant to say "Sent 1.12345678 xvg to.."

Ok so for BTC and LTC you can send an 8 digit number, but XVG is 6 digits?
That's cool, but in that case, you shouldn't be able to enter 8 digits in the send value in the first place.

**Comment by SwenVanZanten** [comment]
Thnx and agreed
