### ISSUE TITLE
Transaction History -> Send transaction details -> Address masking

### ISSUE THREAD

**Issue by Max1us** [vergecurrency/vIOS#92]
**Describe the bug**
When viewing the details of a sent transaction (modal popup), the xvg address is masked. However further down the modal, the full address is visible.

**To Reproduce**
1. View a transaction

**Expected behavior**
If the address was not visible elsewhere on the page, masking it would make sense - but in this case it kind of seems unnecessary?

**Smartphone (please complete the following information):**
 - Device: iPad Mini
 - OS: iOS 12.1.1

**Comment by SwenVanZanten** [comment]
Its a placeholder for when the address is unknown, otherwise the contact name is there.
