### ISSUE TITLE
Transaction History -> Send transaction details modal -> Circular arrow icon

### ISSUE THREAD

**Issue by Max1us** [vergecurrency/vIOS#93]
**Describe the bug**
The two-arrows-in-a-circle icon in the top right hand corner of the details modal indicated (to me) to be some kind of refresh/reload - perhaps to see the latest status of the transaction.
I was surprised that it jumped to the send page, repopulating all the prior details.

**To Reproduce**
1. View a transaction's details

**Expected behavior**
Reload the transaction details into the modal.

**Smartphone (please complete the following information):**
 - Device: iPad Mini
 - OS: iOS 12.1.1

**Comment by Max1us** [comment]
I'd argue that maybe what the icon is depicting is misleading then?

**Comment by SwenVanZanten** [comment]
What kind of icon do you suggest than?

Verstuurd vanaf mijn iPhone
