### ISSUE TITLE
'Normal' keyboard shows when entering XVG amounts in the textfields

### ISSUE THREAD

**Issue by Max1us** [vergecurrency/vIOS#97]
**Describe the solution you'd like**
When entering amounts of XVG to send or receive, could we default the keyboard to show a 'number pad' view, instead of the normal qwerty keyboard for these fields.

**Comment by SwenVanZanten** [comment]
that's not possible on an iPad, the iPhone version does have the numpad

**Comment by marpme** [comment]
You could implement your own "custom" number keyboard

**Comment by SwenVanZanten** [comment]
Very inefficient use of time... as there is not even a bug, just a preference

**Comment by Max1us** [comment]
https://github.com/azu/NumericKeypad
https://github.com/lnafziger/Numberpad
https://github.com/benzado/HSNumericField
