### ISSUE TITLE
Send: When scanning a Wraith QR Code, only half the address is populated

### ISSUE THREAD

**Issue by Max1us** [vergecurrency/vIOS#98]
**Describe the bug**
On the Send screen, when scanning a Wraith QR Code the app only populates half the address into the Recipient Address (it assumes a normal length non-wraith xvg address?)

**To Reproduce**
1. Go to the Send screen
2. Scan a Wraith QR Code (eg from QT Wallet)
3. Address populated is incomplete.

**Expected behavior**
Full length wraith address should be populated

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPad Mini
 - OS: iOS 12.1.1

**Additional context**
I'm assuming I am actually able to currently send to Wraith Addresses?

**Comment by SwenVanZanten** [comment]
#52 related

**Comment by SwenVanZanten** [comment]
Fixed
